modLoader="javafml"
loaderVersion="[40,)"
license="Not specified"

[[mods]]
modId="eggs"
version="1.0.0"
displayName="eggs"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="owenkop, MCreator"

[[dependencies.eggs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




